### ISSUE TITLE
Code release time

### ISSUE THREAD

**Issue by glx15534565855** [OpenRobotLab/HIMLoco#2]
Hi, I wonder how soon will you release the code, since this wonderful work has already accepted. Thanks!

**Comment by pengzhenghao** [comment]
+1

**Comment by JL-Brain** [comment]
+2

**Comment by jnaliu** [comment]
Hi, I hope this message finds you well. 

In Figure 2 of your paper, you illustrate the components of the policy network's input, which include a hybrid internal embedding derived from the robot's historical observations. I am intrigued by the distinction between the explicit velocity \( \hat{v}_t \) and the actual velocity \( v_t \) as depicted in the figure. The paper describes \( \hat{v}_t \) as part of the hybrid internal embedding optimized through contrastive learning to simulate the robot's response. However, the precise definition and role of \( v_t \) within the context of the proprioceptive information are not explicitly detailed in the text I have access to.

Could you please clarify the following:

1. Regarding \( v_t \), how does it relate to the explicit velocity \( \hat{v}_t \)  provided by the proprioceptive sensors, and how is it used within the framework of your hybrid internal model?

Your insights would be invaluable for my understanding of the nuanced aspects of the HIM and its application in agile legged locomotion. I appreciate your time and expertise in elucidating these concepts.

Thank you very much.

Best regards

**Comment by Junfeng-Long** [comment]
v_t is the target of \hat{v}_t, the hybrid internal model gives an estimation of v_t, which is \hat{v}_t. \hat{v}_t is used as a part of policy input to estimate disturbances.

**Comment by Junfeng-Long** [comment]
Sorry for the late. Code is released.
